name: test & build suite
on:
  # configure these to your liking
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - dev
      - main

jobs:
  suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: install npm modules
        run: |
          npm ci
      - name: lint code base
        run: |
          npm run lint --if-present
      - name: build code base
        run: |
          npm run build --if-present
      - name: run test suite
        run: |
          npm test --if-present
